[platformio]
boards_dir = boards

[env:stm32u083]
# Die komplette URL zum Repository muss hier stehen:
platform = https://github.com
board = nucleo_u083rc
framework = ARDUINO_NUCLEO_U083RC
#platform_packages = tool-openocd@https://github.com
tool-stm32duino@https://github.com
framework-arduinoststm32@https://github.com
; Upload and debug settings
upload_protocol = stlink
debug_tool = stlink
upload_command = "C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI.exe" -c port=SWD -w "$SOURCE" 0x08000000 -v -rst
debug_tool = stlink
; Manuelle Zuweisung des Targets, falls nötig
board_debug.openocd_target = stm32u0x
; Serial monitor
monitor_speed = 115200

; Libraries
lib_deps =
    https://github.com/mysensors/MySensors.git#development
    stm32duino/STM32duino RTC@^1.4.0
    closedcube/ClosedCube HDC1080@^1.3.2

; Build flags - STM32U0 compatibility fixes
build_flags =
    -I include
    -I lib/MySensors_patch
    -D ARDUINO_ARCH_STM32
    -D ARDUINO_NUCLEO_U083RC
    -D RTC_ISR_INITS=RTC_ICSR_INITS
    -D RTC_WKUP_IRQn=RTC_TAMP_IRQn
    -D PIN_SPI_SCK=PA5
    -D PIN_SPI_MISO=PA6
    -D PIN_SPI_MOSI=PA7
    -include "include/stm32_aes_fix.h"
